name: skripsi
description: A new Flutter application.


publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  fluttertoast: ^7.1.1
  http: ^0.12.2
  cloud_firestore: ^0.14.1+2
  modal_progress_hud: ^0.1.3
  firebase_auth: ^0.18.0+1
  firebase_core: ^0.5.0
  flutter_svg: ^0.19.0
  fl_chart: ^0.12.0
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true


  assets:
  - images/


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
